config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :doctors, controllers: { registrations: "doctors/registrations" }
  resources :doctors

  resources :clinics

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  
  get "/clinics/:id/add_doctor", to: "clinics#add_doctor", as: :add_doctor_to_clinic
  post "/clinics/:id/update_doctor", to: "clinics#update_doctor", as: :update_doctor_to_clinic
  get "/clinics/:id/remove_doctor/:did", to: "clinics#remove_doctor", as: :remove_doctor_from_clinic

  get "/mybookings", to: "bookings#index_user", as: :user_bookings
  get "/my_bookings", to: "bookings#index_doctor", as: :doctor_bookings

  root to: 'visitors#index'
end

app/models/clinic.rb
# == Schema Information
#
# Table name: clinics
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  latitude   :float
#  longitude  :float
#

class Clinic < ActiveRecord::Base
	has_many :doctors
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
	attr_accessor :doctor_id

	def to_s
		self.name
	end
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy, :add_doctor, :update_doctor, :remove_doctor]
  # before_action :authenticate_user
  # GET /clinics
  # GET /clinics.json
  def index
    if doctor_signed_in?
      if current_doctor.clinic
        redirect_to current_doctor.clinic
      else
        redirect_to new_clinic_path
      end
    end
    if params[:search].present?
      @clinics = Clinic.near(params[:search], 10)
    else
      @clinics = Clinic.all
    end
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)
    if doctor_signed_in?
      current_doctor.clinic = @clinic
      current_doctor.save!
    end
    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_doctor
    @doctors = Doctor.all
  end

  def update_doctor
    d = Doctor.find(clinic_doctor_params[:doctor_id])
    d.clinic = @clinic
    d.save!
    redirect_to @clinic
  end

  def remove_doctor
    d = Doctor.find(params[:did])
    d.clinic = nil
    d.save!
    redirect_to @clinic
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:name, :address)
    end

    def clinic_doctor_params
      params.require(:clinic).permit(:doctor_id)
    end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.erb
<%= simple_form_for(@clinic) do |f| %>
  <%= f.error_notification %>
  
  <div id="gmaps-error"></div>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<script type="text/javascript">
  
jQuery(function() {
  var completer;

  completer = new GmapsCompleter({
    inputField: '#clinic_address',
    errorField: '#gmaps-error'
  });

  completer.autoCompleteInit({
    country: "in"
  });
});
</script>

app/views/clinics/add_doctor.html.erb
<%= simple_form_for @clinic, :url => update_doctor_to_clinic_path(@clinic), :method => :post do |f| %>
	<%= f.input :doctor_id,collection: @doctors%>
	<%= f.submit "Add Doctor" %>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing Clinic</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinic %> |
<%= link_to 'Back', clinics_path %>

app/views/clinics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clinics</h1>
<%= form_tag clinics_path, :method => :get do %>
  <div id="gmaps-error"></div>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clinics.each do |clinic| %>
      <tr>
        <td><%= clinic.name %></td>
        <td><%= clinic.address %></td>
        <td><%= link_to 'Show', clinic %></td>
        <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
        <td><%= link_to 'Destroy', clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clinic', new_clinic_path %>
<script type="text/javascript">
  
jQuery(function() {
  var completer;

  completer = new GmapsCompleter({
    inputField: '#search',
    errorField: '#gmaps-error'
  });

  completer.autoCompleteInit({
    country: "in"
  });
});
</script>

app/views/clinics/new.html.erb
<h1>New Clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clinic.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @clinic.address %>
</p>

<p>
  <strong>Doctors:</strong>
  <ul>
  <% @clinic.doctors.each do |doctor| %>
  <li><%= link_to doctor, doctor %> (<%= link_to "remove", remove_doctor_from_clinic_path(@clinic,doctor) %>)</li>
  <% end %>
  </ul>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=13&markers=#{@clinic.latitude}%2C#{@clinic.longitude}" %>
<br>
<%= link_to 'Add Doctor', add_doctor_to_clinic_path(@clinic), :class => "btn btn-success" %>
<br>
<%= link_to 'Edit', edit_clinic_path(@clinic) %> |
<%= link_to 'Back', clinics_path %>