config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :doctors, controllers: { registrations: "doctors/registrations" }
  resources :doctors

  resources :clinics

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  
  get "/clinics/:id/add_doctor", to: "clinics#add_doctor", as: :add_doctor_to_clinic
  post "/clinics/:id/update_doctor", to: "clinics#update_doctor", as: :update_doctor_to_clinic
  get "/clinics/:id/remove_doctor/:did", to: "clinics#remove_doctor", as: :remove_doctor_from_clinic

  get "/mybookings", to: "bookings#index_user", as: :user_bookings
  get "/my_bookings", to: "bookings#index_doctor", as: :doctor_bookings

  root to: 'visitors#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Clinics', clinics_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>

  <li><%= link_to 'My Bookings', user_bookings_path %></li>
<% elsif doctor_signed_in? %>
  <li><%= link_to 'My Clinic', clinics_path %></li>

  <li><%= link_to 'My Bookings', doctor_bookings_path %></li>
  <li><%= link_to 'Edit account', edit_doctor_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_doctor_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'User Sign in', new_user_session_path %></li>
  <li><%= link_to 'User Sign up', new_user_registration_path %></li>
  <li><%= link_to 'Doctor Sign in', new_doctor_session_path %></li>
  <li><%= link_to 'Doctor Sign up', new_doctor_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Doctors', doctors_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Demo Zeblet" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Demo Zeblet" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>